name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # 📌 Obtener versión desde pom.xml
    - name: Extract Maven project version
      id: project_version
      run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

    # 📦 Subir el JAR como Artifact
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: prueba-api
        path: target/prueba-api-*.jar

    # 🚀 Crear Release y subir el JAR
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.project_version.outputs.version }}
        name: "Release ${{ steps.project_version.outputs.version }}"
        files: target/prueba-api-*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
